# Generated by Django 3.2.5 on 2021-07-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='text',
            field=models.CharField(default='null', max_length=400),
            preserve_default=False,
        ),
    ]
